title: 24Seven.FM Player Privacy
description: Privacy notice for the unofficial 24Seven.FM Player Android application
url: https://codeframe78.github.io
baseurl: /24Seven.FM-Player
markdown: kramdown
strict_front_matter: true
