title: 24Seven.FM Player
description: An unofficial, community-built native Android player for the 24seven.FM radio network
url: https://player.jamesjennison.net
baseurl: ""
markdown: kramdown
strict_front_matter: true
timezone: America/Los_Angeles
repository: James-Jennison/24Seven.FM-Player
github_url: https://github.com/James-Jennison/24Seven.FM-Player
master_url: https://jamesjennison.net
status_url: https://status.jamesjennison.net

exclude:
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
